# Generated by Django 3.2.4 on 2021-07-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent_folder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zero_paper.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('doctype', models.CharField(choices=[('PDF', 'Pdf'), ('IMG', 'Image'), ('XLS', 'Excel'), ('DOCX', 'Docx'), ('TXT', 'Text')], max_length=128)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('folder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zero_paper.folder')),
                ('tags', models.ManyToManyField(to='zero_paper.Tag')),
            ],
        ),
    ]
