# Generated by Django 3.2.4 on 2021-07-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero_paper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
