# Generated by Django 3.2.4 on 2021-07-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zero_paper', '0003_document_folder_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zero_paper.folder'),
        ),
    ]
