name: ZeroPaper actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: remove existing app repo
        run: rm -rf ./zero-paper
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: build docker-compose
        run: docker-compose build
      - name: run docker-compose
        run: docker-compose up -d
        
